// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8_CcYc3B9RecKJE2xuqKLAA7mV8wRfA',
    appId: '1:224754537239:web:3d5dcb3415cdf1658b5d52',
    messagingSenderId: '224754537239',
    projectId: 'sc-management-system-aa21d',
    authDomain: 'sc-management-system-aa21d.firebaseapp.com',
    storageBucket: 'sc-management-system-aa21d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDRWuPBrGbiOeM2Hy8OdBGdxlcZhJoww',
    appId: '1:224754537239:android:1222805329707e9a8b5d52',
    messagingSenderId: '224754537239',
    projectId: 'sc-management-system-aa21d',
    storageBucket: 'sc-management-system-aa21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3IT2M2UT-6mBVwudyOsYjG6Lk56hFv0',
    appId: '1:224754537239:ios:82359989cc0066cb8b5d52',
    messagingSenderId: '224754537239',
    projectId: 'sc-management-system-aa21d',
    storageBucket: 'sc-management-system-aa21d.appspot.com',
    iosBundleId: 'com.example.sportsComplexMs',
  );
}
